### ISSUE TITLE
Karma and Todos for Roy Shchory

### ISSUE THREAD

**Issue by zvili** [TechnionYP5777/SmartCity-Elderly-Support#10]
_From @roy-shchory on October 30, 2016 13:59_

- [x]  Use a picture, photo or distinct avatar.
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page 
- [x]  State that you are not in search for a job

_Copied from original issue: SpartanRefactoring/Spartanizer#621_

**Comment by zvili** [comment]
_From @roy-shchory on October 30, 2016 14:3_

@yossigil Done.

**Comment by zvili** [comment]
_From @RonGatenio on October 30, 2016 18:24_

What an amazing page 
It's so beautiful! 
Here is mine: #584

**Comment by zvili** [comment]
_From @ZivIzhar on October 30, 2016 19:29_

Woo even shushi in this page
Here's mine #644

**Comment by zvili** [comment]
_From @yosefraisman on October 30, 2016 19:32_

Roy, you are making my dreams come true!

Here's my new and updated bucket list:
* High five a musician I like (Paul Simon, for example).
* ~~Visit the most beautiful karma page ever made.~~
* Attend a Technion lecture that's being recorded.
* See the Northern Lights.

Please visit my page too (it's over here #616)

**Comment by zvili** [comment]
_From @inbalzukerman on October 31, 2016 13:23_

Nice Karma pageee 😄 
Check out mine: #684

**Comment by zvili** [comment]
_From @EliaTraore on October 31, 2016 14:2_

brother from another motherrrr 💯 👌 
check this page its lit af #694

**Comment by zvili** [comment]
_From @RonGatenio on October 31, 2016 14:6_

I'm here for Emma's number...  But I think you lied 😢

**Comment by zvili** [comment]
_From @Shahar-Y on October 31, 2016 14:25_

I am here to bask at the greatness and awesomeness of your karma page. Not disappointed. 
#665 and stuff.

**Comment by yossigil** [comment]
Please write here a list of issues that you completed for sprint 1

@zvili @idabran

**Comment by roy-shchory** [comment]
worked on and completed issues #14 and #15 with ther rest of the family(team members)  @zvili @yossigil  @idabran

**Comment by inbalzukerman** [comment]
As decided with our guide, Karma issues should be closed in our project.
