### ISSUE TITLE
Test "ApplicationManager"

### ISSUE THREAD

**Issue by EliaTraore** [TechnionYP5777/SmartCity-Elderly-Support#102]
currently not tested at all

**Comment by EliaTraore** [comment]
After discussion with the applications team, we concluded that the overhead of writing tests for such a class is unnecessary, considering that the correctness is verified through every application developed for the system.

**Comment by inbalzukerman** [comment]
Since the class `ApplicationsHandlerTest` is still part of our project, this issue cannot be closed.
Moreover, I think further discussion in this matter with the rest of the group is needed.
