### ISSUE TITLE
Morbidity 

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5777/SmartCity-Elderly-Support#105]
Elia, this may be a fun issue, an issue you may wish to ignore by closing, or discuss with friends.

I just noticed the code containing stuff such as `kill elderly`... A more gentle way one may consider is using terms such as client and demise?

**Comment by roy-shchory** [comment]
@yossigil 
Trump is elected the pc age is gone.
We are trying to make smart houses great again!

**Comment by EliaTraore** [comment]
also, as some of the people in our team pointed out - 
- no milestone
- no labels

yogi.karma --

**Comment by inbalzukerman** [comment]
Changes have been made accordingly and @roy-shchory will take care of further PC issues, as issue #114 is in proccess

**Comment by yossigil** [comment]
:+1:
