### ISSUE TITLE
hide the need for Platform.runLater from the app developers

### ISSUE THREAD

**Issue by RonGatenio** [TechnionYP5777/SmartCity-Elderly-Support#106]
currently the developer must use Platform.runLater in his sensor's listeners, and in onLoad.
we need to hide this from him.

bad example for onLoad:
<pre>
@Override public void onLoad() {
        String sensorId = "00:00:00:00:00:01";
        try {
            subscribeToSensor(sensorId, SosSensor.class, sosSensor -> {
            String t = "SOS " + (sosSensor.isPressed() ? "" : "Not ") + "Pressed";
<b>
            Platform.runLater(() -> sosController.killElder());
</b>
            });
        } catch (SensorNotFoundException e) {
            e.printStackTrace();
        }
    }
</pre>

**Comment by RonGatenio** [comment]
Note that  Platform.runLater is required to run javafx stuff in the javafx thread (created by Application.launch). 
Can't run javafx stuff outside that thread...
BTW, this way I hate javafx

**Comment by SharonKL** [comment]
@RonGatenio fyi, same applies for swing applications. We don't have a better alternative unless you want to program our own GUI library using SFML or OpenGL or something 😁 

#nohateforjavafx

**Comment by RonGatenio** [comment]
@SharonKL we should make our own GUI library with OpenGL and a lot of 3D stuff :smile:
