### ISSUE TITLE
Contact the appropriate contacts in case of emergency

### ISSUE THREAD

**Issue by EliaTraore** [TechnionYP5777/SmartCity-Elderly-Support#108]
As mentioned in the comments to #48, one requirement is the following method - 
`alert(String appId, String msg, EmergencyLevel elvl)`

This method will have to reach the registered contacts in the requested form (phone, SMS or email) so in order to complete it we will have to:
- [ ] Conduct some research on the best way to send an SMS through a java app
- [ ] Conduct some research on the best way to send make a phone call through a java app
- [ ] Implement the method `alert`

The issue will be closed after the aforementioned goals are reached.

**Comment by inbalzukerman** [comment]
What about some research on emailing through a java app?

**Comment by EliaTraore** [comment]
That's an easier task. Sending a email is free, the whole process is checked less (for example, there are no checks that the sender address is really their address) and there's `JavaMail` that can be used and have an nice API for sending emails.
On the other hand, SMS & phone calls are originally paid services, and requires a phone number or something of the sort. as a result, most API that relate to them have some costs that need to be considered. Even if we assume that a smart house some phone-call provider, there's the question of how to simulate in any future presentations, since we'll be running the system from laptops who don't. 
So "research" in that sense means:
- reviewing any free services 
    - e.g. looking into voice over IP
- reviewing payed services
    - e.g. twilio - https://www.twilio.com/
- considering which assumptions can be made about the house (available WiFi? calls provider? - this will probably be brought up for a group discussion if we get there)

So while sending emails isn't completely without research, its not beyond the normal level of research derived from using new code, unlike SMS & phone calls, so it didn't feel as important to mention.

**Comment by inbalzukerman** [comment]
@EliaTraore  and @RonGatenio -
Except of one method `UserInformation` is basically done, feel free to work on `alert` 😄 
(I'l try not to ruin in with git conflicts 😅 )

**Comment by SharonKL** [comment]
Possibly a way to send SMS messages using emails:
http://www.howtogeek.com/howto/27051/use-email-to-send-text-messages-sms-to-mobile-phones-for-free/

**Comment by inbalzukerman** [comment]
In our discussion today we've reached the following conclusions:
* The options to send Emails and SMSs will be checked 
* No automatic phone calls will be made, in case a phone call will be required- a message will be sent to the system-admin

**Comment by EliaTraore** [comment]
As a result of research and team discussions, we decided that the implementation of `alert`  will forward requests to call or send SMSs to contacts to the community manager, which will have access to such services (#121).
The ability to contact via email was implemented in the last commit mentioning this issue, and so this issue can be closed.
