### ISSUE TITLE
Add javafx.concurrent support in the SmartHouseApplication API

### ISSUE THREAD

**Issue by RonGatenio** [TechnionYP5777/SmartCity-Elderly-Support#109]
Currently all of the javafx applications in the system (including the systemCore and the 3rd party applications) run on the same thread (the javafx's thread created by javafx in `Application.launch()`).
So without javafx.concurrent support we face a big problem...
If a developer has some time consuming calculation, the entire house will get stuck while waiting for that application to finish its work. This is very bad!

# TL;DR
We need to find a way to run each application in a unique javafx thread, 
OR (if the first is not possible)
add threading support inside the `SmartHouseApplication` for time consuming calculations.

read more about javafx.concurrent:
- [Oracle - Concurrency in JavaFX](http://docs.oracle.com/javafx/2/threads/jfxpub-threads.htm)
- [Oracle - JavaFX: Interoperability](https://docs.oracle.com/javase/8/javafx/interoperability-tutorial/concurrency.htm)

**Comment by SharonKL** [comment]
http://docs.oracle.com/javafx/2/threads/jfxpub-threads.htm

just saying that running each application as an independant program might have been easier 😛

**Comment by RonGatenio** [comment]
> just saying that running each application as an independant program might have been easier 😛

NEVERRRRRRR!

**Comment by SharonKL** [comment]
#justsayingthatrunningeachapplicationindependantlymighthavebeeneasierthantryingtohavemultithreadedprogramsusingjavafx

**Comment by RonGatenio** [comment]
#doingeverythingwithsocketsisugly

**Comment by RonGatenio** [comment]
BTW, @SharonKL won this fight...
The developers can easily get the system stuck.
However, we can assume that we will review third party apps before placing them on the market… We will not allow those kind of apps to exist.

So, javafx.concurrent support is already available for the developers, they can use it to make better apps (apps that won't get stuck)… We don't need to add stuff to the API for this…
