### ISSUE TITLE
Karma and Todos for Sharon Kuninin

### ISSUE THREAD

**Issue by zvili** [TechnionYP5777/SmartCity-Elderly-Support#11]
_From @SharonKL on October 30, 2016 10:35_

- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon:
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page; FYI, here is my description
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box

_Copied from original issue: SpartanRefactoring/Spartanizer#614_

**Comment by zvili** [comment]
_From @SharonKL on October 30, 2016 10:37_

@YossiGil: Done.

**Comment by zvili** [comment]
_From @yosefraisman on October 30, 2016 12:10_

@SharonKL, your karma page truly is astounding, hope you get a chance to look at mine! #616

**Comment by zvili** [comment]
_From @ylevv on October 30, 2016 12:23_

What a lovely Karma Page :smile:

**Comment by zvili** [comment]
_From @RonGatenio on October 30, 2016 15:49_

This is a great page Kuninin. Good job! 👍

**Comment by zvili** [comment]
_From @EliaTraore on October 31, 2016 13:57_

what a lovely page 😍 check out mine #694

**Comment by yossigil** [comment]
Please write here a list of issues that you completed for sprint 1

@zvili @idabran

**Comment by SharonKL** [comment]
Issues #14 and #15, along with the other members of the group

@yossigil @zvili @idabran

**Comment by roy-shchory** [comment]
![frabz-you-abandoned-me-a291ce](https://cloud.githubusercontent.com/assets/23057062/24199044/e22106e8-0f10-11e7-8a47-b9db98b6a985.jpg)
