### ISSUE TITLE
Create a graphical representation of the sensors in the smart house

### ISSUE THREAD

**Issue by SharonKL** [TechnionYP5777/SmartCity-Elderly-Support#113]
A GUI that will graphically show where each sensor in the house is found

**Comment by yossigil** [comment]
And how this information would be maintained and/or updated? Not sure this is a good idea.

**Comment by SharonKL** [comment]
The information is already stored in the system and can be updated using relevant methods. This GUI will be used to easily access the information and make changes using a friendly graphical interface. By `where each sensor is found` I mean in what room (i.e. Kitchen, Living Room, etc...) not the exact GPS coordinates.

As for how we thought to maintain the original data regarding each sensor's location, this will be done by the technician that will install the system in the house (he/she will select where each sensor was installed so applications can poll this data).

**Comment by yossigil** [comment]
OK

**Comment by SharonKL** [comment]
![](https://s30.postimg.org/psj2xv6sx/sensors_mapping_gui_mockup.png)

Fast mock-up, no 3D yet

**Comment by inbalzukerman** [comment]
Looks Amazing!!!
Btw, should we add the "Hallway" option to the `SensorLocation` enum?

**Comment by SharonKL** [comment]
Definitely not required now, we will talk about that today 😄

**Comment by yossigil** [comment]
If you can use names in Hebrew, your application would be more useful:

1. חדר שינה
2. חדר הורים
3. שירותים
4. ממד

Add more names and you get amazing functionality at low implementation cost

**Comment by SharonKL** [comment]
![](https://s27.postimg.org/e1vf6phgz/house_mapping_demo.gif)

For now the GUI knows when new sensors are being registered and adds them to the interface. Next steps will include being able to change the sensor location, and working on the left pane (graphical house representation).

_I am aware of the fact the ids for the simulators are the same, this will be changed/fixed._

**Comment by yossigil** [comment]
Nice start

**Comment by SharonKL** [comment]
![](https://s23.postimg.org/cx2n65dt7/house_mapping.gif)
