### ISSUE TITLE
Karma and Todos for Yarden Lev

### ISSUE THREAD

**Issue by zvili** [TechnionYP5777/SmartCity-Elderly-Support#12]
_From @ylevv on October 29, 2016 22:32_

duplicates #330 
- [x]  Use a picture, photo or distinct avatar. Don't use an automatic icon
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page;
- [x]  State that you are (not) in search for a job

_Copied from original issue: SpartanRefactoring/Spartanizer#598_

**Comment by zvili** [comment]
_From @ylevv on October 29, 2016 22:35_

@yossigil Done?

**Comment by zvili** [comment]
_From @RonGatenio on October 29, 2016 22:58_

This is a beautiful karma page. Good job! 😸 👍

**Comment by zvili** [comment]
_From @yossigil on October 30, 2016 2:33_

Cleanup the contents so that only the todos are there.
Add milestone and quality and teaching labels.
Use full name in link.

**Comment by zvili** [comment]
_From @geniashand on October 30, 2016 9:1_

great page 👍 🍡 
You're invited to check mine

**Comment by zvili** [comment]
_From @SapirBismot on October 30, 2016 10:21_

Your Karma Page is very nice 💯 
#612

**Comment by zvili** [comment]
_From @SharonKL on October 30, 2016 10:41_

not bad 👍 
#614

**Comment by zvili** [comment]
_From @ylevv on October 30, 2016 10:51_

@yossigil Did you mean I should change my username? "ylevv" stands for **Y**arden **Lev**, same as "idabran" for **I**tai **Dabran**

**Comment by zvili** [comment]
_From @yossigil on October 31, 2016 0:26_

OK didn't notice that

**Comment by yossigil** [comment]
Please write here a list of issues that you completed for sprint 1

@zvili @idabran

**Comment by ylevv** [comment]
I worked on issues #14 and #15. I completed them with the other members of the team.
@yossigil @zvili @idabran

**Comment by inbalzukerman** [comment]
As decided with our guide, Karma issues should be closed in our project.
