### ISSUE TITLE
MainSystemGUI's functionality 

### ISSUE THREAD

**Issue by inbalzukerman** [TechnionYP5777/SmartCity-Elderly-Support#120]
@roy-shchory -
The class you have implemented the Main System GUI (namely: `MainSystemGUI` ) might be redundant ( 😨 )
Please pay attention to the class `SystemCore` - currently it's invoking (I had no better verb here) the GUI of the glorious house-mapping GUI made by @SharonKL. It is supposed to invoke the main-system GUI therefore the `MainSystemGUI` is unnecessary as I see it.

I'm working on "connecting" the user information GUI (#16) to the backend logic we've created, therefore I noticed this matter.

**Comment by SharonKL** [comment]
The controller can't be redundant, it is in charge of reacting and changing the GUI. The `MainSystemGUI` *might* be redundant, but it can be used to only open the main GUI (if needed, to check everything is ok in that specific GUI) instead of running the whole system, as is done in the `SystemCore`.

**Comment by inbalzukerman** [comment]
Clearly the controller is not redundant, and as the issue's title suggest, I'm talking about `MainSystemGUI` which is not `MainSystemGuiController`. 
The part of the main system gui which I was responsible of will not work without information (such as the `user` ) which is saved in the `SystemCore`. 
Yet again, I said it _might_ be redundant and wanted to let @roy-shchory  know he should change `SystemCore` anyhow.

**Comment by SharonKL** [comment]
In the original comment it was said `the Main system controller`, I thought you were talking about the controller. Any way, this can be closed now I guess?
