### ISSUE TITLE
Karma and Todos for Alex V.

### ISSUE THREAD

**Issue by alexvitho** [TechnionYP5777/SmartCity-Elderly-Support#123]
_From @alexvitho on October 28, 2016 18:30_

#330
- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon:
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page; FYI, here is my description:
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box:

_Copied from original issue: SpartanRefactoring/Spartanizer#573_

**Comment by inbalzukerman** [comment]
As decided with our guide, Karma issues should be closed in our project.
