### ISSUE TITLE
Karma and Todos for Ron Gatenio

### ISSUE THREAD

**Issue by zvili** [TechnionYP5777/SmartCity-Elderly-Support#13]
_From @RonGatenio on October 29, 2016 11:34_

- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon.
- [x]  Make sure you present yourself by a readable **nick**.
- [x]  Describe yourself in the bio page.
- [x]  State that you are (not) in search for a job.

_Copied from original issue: SpartanRefactoring/Spartanizer#584_

**Comment by zvili** [comment]
_From @RonGatenio on October 29, 2016 11:37_

@YossiGil: Done.

**Comment by zvili** [comment]
_From @yossigil on October 29, 2016 11:53_

Keep this one open. Assign labels teaching and quality-assurance. Edit the content so it looks more decent. Add a milestone.

**Comment by zvili** [comment]
_From @yossigil on October 29, 2016 19:6_

Assign yourself please

**Comment by zvili** [comment]
_From @ylevv on October 29, 2016 22:53_

That's a really nice Karma Page! 🎉 
Take a look at mine #598 😄

**Comment by zvili** [comment]
_From @SapirBismot on October 30, 2016 10:19_

**Ron, this is a very nice Karma Page** 👍 
 #612

**Comment by zvili** [comment]
_From @SharonKL on October 30, 2016 10:42_

👌 
#614

**Comment by zvili** [comment]
_From @orenafek on October 30, 2016 15:27_

Awesome Karma Page :)
I hope you'll love mine #624

**Comment by zvili** [comment]
_From @ZivIzhar on October 30, 2016 19:28_

nice nice shushi
what's that? : #644

**Comment by zvili** [comment]
_From @tonylekhtman on October 31, 2016 7:18_

Cool Page!

**Comment by zvili** [comment]
_From @inbalzukerman on October 31, 2016 13:25_

Such a nice Karma page!! 🏆 😃 
Check out mine- #684

**Comment by zvili** [comment]
_From @EliaTraore on October 31, 2016 14:0_

omg this is the best page everr 😲 
check this one out #694

**Comment by zvili** [comment]
_From @roy-shchory on October 31, 2016 14:2_

what a lovely page! i showed it to my firend Ema Stone and she wanted you to call her for a chat.
her number is on my Karma page in #621

**Comment by zvili** [comment]
@RonGatenio - Please close this issue

**Comment by zvili** [comment]
@RonGatenio - Sorry, Ori is right. This issue must remain opened.

**Comment by yossigil** [comment]
Please write here a list of issues that you completed for sprint 1

@zvili @idabran

**Comment by RonGatenio** [comment]
I completed the issues #14 and #15 on Sprint1, with the rest of the team.
@yossigil @zvili @idabran

**Comment by inbalzukerman** [comment]
As decided with our guide, Karma issues should be closed in our project.
