### ISSUE TITLE
Plan sprint 2

### ISSUE THREAD

**Issue by roy-shchory** [TechnionYP5777/SmartCity-Elderly-Support#15]
plannig sprint 2 according to the user stories we created in sprint 1

**Comment by SharonKL** [comment]
I think user registration and ability to update information should be added as soon as possible. Probably some basic sensor handling as well.

**Comment by inbalzukerman** [comment]
I agree- new issues will be opened 😄

**Comment by SharonKL** [comment]
Sprint 2 has been planned and relevant cards (user stories) have been moved to the dedicated list.
