### ISSUE TITLE
Add interface to communicate with sensors

### ISSUE THREAD

**Issue by SharonKL** [TechnionYP5777/SmartCity-Elderly-Support#25]
An interface that sensors will use to send information to the system, which will be stored in the database and accessed by apps. In addition, the interface will allow communication in the opposite direction (sending information to sensors that require it).

**Comment by inbalzukerman** [comment]
TODO: 
* Create the interface itself 
* implement the required methods in the sensor's classes ( @ylevv  @SharonKL )

**Comment by SharonKL** [comment]
This issue is a bit misleading (thanks a lot @SharonKL), in the last meeting we changed the way communication works from using interfaces, to sending JSon messages over the internet.

Since issue #52 is responsible for managing the data received from sensors, I suggest opening a new issue that will be responsible for receiving messages from sensors (in our case, register and update messages).

@inbalzukerman @EliaTraore @ylevv your opinions? If you agree I will open the issue

**Comment by ylevv** [comment]
I agree 👍

**Comment by SharonKL** [comment]
Oh, Issue #41 already talks about establishing communication. So my suggestion is to simply close this issue. 

@inbalzukerman @EliaTraore @ylevv

**Comment by inbalzukerman** [comment]
I agree- Issue #52 is all about the back-end of establishing the communication and #41 is more about the GUI part of it

Good observations there @SharonKL  😄  👍
