### ISSUE TITLE
Add interface to communicate with apps ["ApplicationHandler"]

### ISSUE THREAD

**Issue by SharonKL** [TechnionYP5777/SmartCity-Elderly-Support#26]
An interface that will allow communication between the system (especially the system database) and the different apps that will added to the system.

It's **current** required functionalities - 
- [x] Receive registration requests from the applications, allowing them to listen to different sensors in the system - 
     - [x] requests for update on change which is defined by a predicate 
     - [x] requests for update on < time >
- [x] Receive queries about the state of different sensors
- [x] Send information to the applications on changes in sensors data, as per requests
- [ ]  ~Receive alerts on abnormalities from the applications and contact the right authority (see #23)~ [moved to #75]

<br>

This issue will be closed only after:
- the for-mentioned functionalities are implemented
- the process of installing/loading and running the application on a thread is fully developed and implemented (with the assistance of the application team). [this might be moved to #75 as well]

**Comment by inbalzukerman** [comment]
TODO:

* Create the interface itself
* implement the required methods in the sensor's classes ( @roy-shchory  @RonGatenio )

**Comment by inbalzukerman** [comment]
@EliaTraore  please move the class "ApplicationHandler" to a separate java file (Not inside MainSystem)

**Comment by EliaTraore** [comment]
TODO: document that the listeners expect the full table.

**Comment by EliaTraore** [comment]
TODO: 
- [ ] add `List Inquire(String CommercialName)` that returns the ids associated with the comName
- [ ] refactor `ApplicationHandler` to work with the sensorID in other methods (the app get the list and chooses which interests her)

**Comment by SharonKL** [comment]
@EliaTraore 😄 

btw, these are for the second iteration, right?

**Comment by EliaTraore** [comment]
Those are simple modification so I'll implement them later today. We're currently ~writing~ finishing the `DatabaseHandler` so I can clearly see it will make it much easier on all parties if I'll add this behaviour now. (and considering thats the desired behaviour its not wasted code)
<br>
still #TeamCommName tho, dont worry :grin:
