### ISSUE TITLE
Add wiki page to describe the system overview

### ISSUE THREAD

**Issue by SharonKL** [TechnionYP5777/SmartCity-Elderly-Support#28]
Part of our meeting was dedicated to deciding our system structure. A wiki page should be created to describe this structure and explain the different parts of the system.

**Comment by SharonKL** [comment]
Has been created and filled with content

**Comment by yossigil** [comment]
please add a link to the deliverable, i.e., wikpage.

**Comment by SharonKL** [comment]
The **System Overview** wiki page can be accessed [here](https://github.com/TechnionYP5777/SmartCity-Elderly-Support/wiki/System-Overview)
