### ISSUE TITLE
First Team Meeting 

### ISSUE THREAD

**Issue by inbalzukerman** [TechnionYP5777/SmartCity-Elderly-Support#3]
Today we had meeting in which we decided the following things:

* Our weekly meetings will hold on Tuesdays, 16:30 - 18:30
* Our contact with the staff is me (Inbal Zukerman)

On our meeting today we worked on the first report together and initialized a maven Java project.

Present: @RonGatenio @roy-shchory @EliaTraore @SharonKL @ylevv  and Inbal Zukerman

**Comment by zvili** [comment]
@inbalzukerman 
- Where is your first report located ?
- Your meetings with the staff on Tuesdays will last about 1 hour. Please sync with other groups who would also like their meetings on the same week days.
- A draft of your project backlog should be ready "before" our meeting.

@idabran - please confirm your availability on Tuesdays. Thanks.

**Comment by inbalzukerman** [comment]
@zvili -

* We didn't finish our first report yet, we have to complete some final touches.
* We plan to meet every tuesday as a gruop for the two hours mentioned, and whenever you and @idabran  can we will meet with you (hopefully between the hours mentioned)

We will do our very best so the draft of the backlog will be ready before the meeting 😄

**Comment by zvili** [comment]
:+1:

**Comment by idabran** [comment]
I'm available on Tuesdays

**Comment by zvili** [comment]
:-)

On Nov 23, 2016 7:59 AM, Itai Dabran <notifications@github.com> wrote:

I'm available on Tuesdays

**Comment by yossigil** [comment]
@inbalzukerman : where is the report?

**Comment by inbalzukerman** [comment]
@yossigil - We didn't finish our first report yet, we have to complete some final touches. Matching Issues have been opened and it will be ready by the next meeting scheduled with @idabran and @zvili

**Comment by yossigil** [comment]
Where is the **unfinished** work?

**Comment by inbalzukerman** [comment]
https://docs.google.com/document/d/1OY1iSeRCgkJI9jjNh3pCssqRkkCPj-HlBT0AwvcS3T4/edit?usp=sharing
