### ISSUE TITLE
Develop the GUI for the stove sensor simulation

### ISSUE THREAD

**Issue by inbalzukerman** [TechnionYP5777/SmartCity-Elderly-Support#31]
for more info: #17
Create the GUI for simulating the stove sensor.
This GUI is based on the #27 interface

**Comment by SharonKL** [comment]
Done 😄 

![Stove Sensor GUI Demonstration](http://i.giphy.com/l2JhCprna5bGObR5K.gif)

**Comment by SharonKL** [comment]
Design is minimalistic, but gotta start somewhere before moving to 3D and VR

**Comment by inbalzukerman** [comment]
Amazing work!! 🎊 🎉 🎉 😍 😄

**Comment by RonGatenio** [comment]
Looks great!!! Good job @SharonKL  👏  👏  👏 👏

**Comment by yossigil** [comment]
Good job team!
