### ISSUE TITLE
Create an App/Module Installer function

### ISSUE THREAD

**Issue by RonGatenio** [TechnionYP5777/SmartCity-Elderly-Support#39]
A function of _main_system_obj_
This function will allow to install external apps/modules at run-time
- Will receive a path to the .jar file of the app/module.
- The app will be added to the run-time of the system with the `ClassLoader`
    note that app must have a class that extends our abstract API #50.
- The _main_system_obj_ will call the app's setMainSystemInstance(main_system_obj) and onInstall()(explained in #50)
- The _main_system_obj_ will create a thread and call the app's main() (explained in #50)

More explanation on dynamic java code:
[Add dynamic Java code to your application - Write code that can respond to changes at runtime](http://www.javaworld.com/article/2071777/design-patterns/add-dynamic-java-code-to-your-application.html)

**Comment by RonGatenio** [comment]
The Installer is complete.
It can load classes from a .jar file or from a list of names of classes.

**Comment by inbalzukerman** [comment]
Amazing work! 😃  👍  🎉
