### ISSUE TITLE
Karma and Todos for Elia Traore

### ISSUE THREAD

**Issue by zvili** [TechnionYP5777/SmartCity-Elderly-Support#4]
_From @EliaTraore on October 31, 2016 13:45_

- [X]  Use a picture, photo or distinct, familiar, personal 
avatar. Don't use an automatic icon (we need this to be able to identify you in the tens of students we have)
- [X] Present yourself by a not too rude **nick**  
- [X]  Describe yourself in the bio page; FYI, here is my description
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box

_Copied from original issue: SpartanRefactoring/Spartanizer#694_

**Comment by zvili** [comment]
_From @EliaTraore on October 31, 2016 13:45_

@YossiGil: Done.

**Comment by zvili** [comment]
_From @roy-shchory on October 31, 2016 14:6_

cool page fam, very lit very tight
for bottle flip videos and worldstar highlights go to #621

**Comment by zvili** [comment]
_From @Shahar-Y on October 31, 2016 14:23_

Hello, Elia. 
I am here as summoned. 
May your karma page be as amazing as Inbal and Amir's. I have dubts, tho.
You are allowed to visit mine at #665 and admire its greatness. 
Live long and prosper

**Comment by zvili** [comment]
_From @RonGatenio on October 31, 2016 18:12_

You couldn't have done it better, this page is great! 😃

**Comment by orimarco** [comment]
@EliaTraore  please make a list of issues you completed and working on.

**Comment by EliaTraore** [comment]
@orimarco like the rest of the team, in sprint one i worked on and completed issues #14 and #15. In the current sprint ive completed issue #49, and currently working on #26.

**Comment by inbalzukerman** [comment]
As decided with our guide, Karma issues should be closed in our project.
