### ISSUE TITLE
Design a sensor installer

### ISSUE THREAD

**Issue by RonGatenio** [TechnionYP5777/SmartCity-Elderly-Support#41]
This code should be in the system's core, and should be accessible by the user/worker via the GUI.

On installation (some ideas):
- The sensor and the system will establish communication
- The system will give the sensor a unique ID
- The system will allocate space in it's database for the sensor
From now, when the system receives data from the sensor, it will be written to the previously allocated space.

**Comment by yossigil** [comment]
Ideas:
- Define a protocol in a clear way, and even start writing tests for the protocol.
- Define a class `Sensor`.

**Comment by SharonKL** [comment]
Handling of registration messages has been added to system package (with the help of @ylevv).
