### ISSUE TITLE
Select a JSON parsing library

### ISSUE THREAD

**Issue by SharonKL** [TechnionYP5777/SmartCity-Elderly-Support#42]
In accordance with our meeting today, it looks like JSON seems to be a pretty good data interchanging format. There are several libraries that support parsing and construction of files in this format, most notable ones can be found in the following SO thread:

http://stackoverflow.com/questions/2591098/how-to-parse-json-in-java

**Comment by roy-shchory** [comment]
i've used the google jason library Gson in another project and i think it would be the best fit for our needs.
heres how to add it tou our maven project:
https://sites.google.com/site/gson/gson-user-guide/using-gson-with-maven2
and heres a user guide:
https://sites.google.com/site/gson/gson-user-guide

**Comment by yossigil** [comment]
@roy-shchory : it would be better if you summarize the pros and cons, so people just do not take your word of it.

**Comment by yossigil** [comment]
#11 : Huh an issue with six assignees....Everyone is responsible and no one is. And, at the end of the day, this issue is a minor implementatio detail that should concern only the one or two people that deal with it.

@zvili @idabran @AdiOmari @orimarco @yh-github

**Comment by yossigil** [comment]
Trying to help you guys, I am closing this issue. I think it is better if you define a new issue with concrete person in charge, whose title is: Produce a demo parser, or better yet, "Json to parse/unparse" class `Event`.
