### ISSUE TITLE
Create the basic sensor class

### ISSUE THREAD

**Issue by SharonKL** [TechnionYP5777/SmartCity-Elderly-Support#44]
Under a package named "sensors", a basic class called "Sensor" should be created. This class will function as a template for future sensors (and simulations) that will be implemented.

**Comment by yossigil** [comment]
:+1:

**Comment by roy-shchory** [comment]
maybe consider making a sensorID class in case we want to replace it from string to something else @SharonKL @ylevv

**Comment by SharonKL** [comment]
Considering this ID will be exchanged in JSON messages and can be easily represented as an integer or string, I think wrapping this information in a class wouldn't achieve too much.

For now I think going with a simple string is enough

**Comment by yossigil** [comment]
I think your objective function should be to make the current version run, and worry about extensions later.

**Comment by inbalzukerman** [comment]
Looks like the abstract class for a sensor is implemented 😄 
What's missing to close this issue?

**Comment by SharonKL** [comment]
Methods that implement similar functionality required by all sensors (registration, sending update messages, etc...)
