### ISSUE TITLE
Karma and Todos for Inbal Zukerman

### ISSUE THREAD

**Issue by zvili** [TechnionYP5777/SmartCity-Elderly-Support#5]
_From @inbalzukerman on October 31, 2016 13:14_

- [x]  Use a picture, photo or distinct, familiar, personal 
avatar. 
- [x] Present yourself by a not too rude **nick**  
- [x]  Describe yourself in the bio page
- [x]  State that you are (not) in search for a job

_Copied from original issue: SpartanRefactoring/Spartanizer#684_

**Comment by zvili** [comment]
_From @inbalzukerman on October 31, 2016 13:17_

@YossiGil: Done.

**Comment by zvili** [comment]
_From @amirsagiv83 on October 31, 2016 13:24_

OMG. I think this Karma page is one of the most amazing things I have ever seen!

you should check out mine. please. I'm begging. #619

**Comment by zvili** [comment]
_From @Shahar-Y on October 31, 2016 13:30_

Wow! Inbal's karma page!! 
What more can life offer me, now that iv'e seen it?

Visit mine at #665

**Comment by zvili** [comment]
_From @roy-shchory on October 31, 2016 14:5_

this page is almost as holy as jerusalem.
for entertaiment please enter #621

**Comment by zvili** [comment]
_From @yaelAmitay on October 31, 2016 14:16_

this karma page is amazing! :)

**Comment by zvili** [comment]
_From @RonGatenio on October 31, 2016 18:9_

This is the most beautiful karma page here. Great job! 👍

**Comment by zvili** [comment]
_From @AdiOmari on November 1, 2016 7:54_

👍 looks good. Add teaching and quality assurance labels.

**Comment by zvili** [comment]
_From @yossigil on November 12, 2016 19:13_

![image](https://cloud.githubusercontent.com/assets/12775400/20240260/c37e9d68-a91c-11e6-85b1-99f00bd13221.png)

**Comment by zvili** [comment]
_From @yossigil on November 12, 2016 19:15_

I could not find your personal TODOs becuas you are not listed as the assiggnee for this issue.

**Comment by zvili** [comment]
_From @inbalzukerman on November 12, 2016 19:23_

@yossigil - I'm sorry, i didn't really got in hand with those github functionalities when i opened the issue. I added myself as an assignee right now.

**Comment by zvili** [comment]
_From @yossigil on November 12, 2016 19:25_

As long as we follow a positive gradient ...

**Comment by zvili** [comment]
_From @inbalzukerman on November 12, 2016 19:27_

Unfortunately every time i try to change a parameter name (not to be d) the Spartanizer fixes it to be d again which causes the warning. Should i not accept the Spartanizer's tip?

**Comment by zvili** [comment]
_From @inbalzukerman on November 12, 2016 19:29_

![image](https://cloud.githubusercontent.com/assets/23147895/20240359/08d386b0-a91f-11e6-9b40-5d723b714ed5.png)

**Comment by zvili** [comment]
_From @yossigil on November 12, 2016 19:48_

Ok, I fixed this for you. Take a look. Also, if you check the file you modified, you will find a similar bug to the one you had. You could gain ooldles of good Karma by fixing the bug.
You can get even more Karma, if you identify commonalities and refactor.
@rodedzats @yonzarecki @ZivIzhar @EliaTraore

**Comment by yossigil** [comment]
Please write here a list of issues that you completed for sprint 1

@zvili @idabran

**Comment by inbalzukerman** [comment]
On sprint 1 we worked on issues #14 and #15- i've completed them along with the other members of the group.

@yossigil @zvili @idabran

**Comment by inbalzukerman** [comment]
As decided with our guide, Karma issues should be closed in our project.
