### ISSUE TITLE
Create an abstract class for the apps/modules

### ISSUE THREAD

**Issue by RonGatenio** [TechnionYP5777/SmartCity-Elderly-Support#50]
Every app/module must extend this class.

This class will have the following functions:
- setMainSystemInstance(_main_system_obj_)
    This will add the _main_system_obj_'s instance to the app. Later the app could ask for service requests directly from the _main_system_obj_.
- abstract onInstall()
    Will be implemented by the developer. Will define the setup of the app (checking if the relevant sensors are installed, subscribing to them...). _main_system_obj_ will call this when the app is installed (#39)
- abstract main()
    This will be implemented by the developer Here the app will define all of its main code.
    The _main_system_obj_ will call this function in a new thread, after the installation process is done.
-  subscribeToSensor(_sensor_ID_, _function_to_run_, _predicate_on_database_)
    This add _function_to_run_ to the sensors Listeners list in the database. If a change in the sensor's data_page (the change is defined by the _predicate_on_database_) will occur,  _function_to_run_ will be called by the _main_system_obj_.
- checkIfSensorExists(_sensor_ID_)
    Will allow the developer to check if a sensor exists. If not he could prevent the app from being installed.

The ideas for this API are written here: #40

**Comment by yossigil** [comment]
:+1:

**Comment by inbalzukerman** [comment]
Looks like the abstract class is implemented ("BaseApplication")
What's missing?

**Comment by inbalzukerman** [comment]
@RonGatenio @roy-shchory  ?

**Comment by roy-shchory** [comment]
Minor changes are left to be done, will be closed soon @inbalzukerman

**Comment by RonGatenio** [comment]
This issue can be closed. More issues on this topic will be opened
@inbalzukerman
