### ISSUE TITLE
Add a wiki page about the JavaFX library

### ISSUE THREAD

**Issue by SharonKL** [TechnionYP5777/SmartCity-Elderly-Support#51]
The wiki page will present the library, its uses and how to construct a functional GUI using the library.

**Comment by yossigil** [comment]
:+1:

**Comment by SharonKL** [comment]
As I have found myself often repeating the official tutorial or other good tutorials, I have decided to write an overview of the library, and leave the explanation of the library for existing, much better, tutorials.

The wiki can be found [here](https://github.com/TechnionYP5777/SmartCity-Elderly-Support/wiki/Writing-a-JavaFX-Application).

**Comment by SharonKL** [comment]
As for a code example, [this directory](https://github.com/TechnionYP5777/SmartCity-Elderly-Support/tree/master/src/main/java/il/ac/technion/cs/eldery/sensors/simulators/stove/gui) will contain a JavaFX used in our project.

**Comment by SharonKL** [comment]
Added another chapter explaining about the components of a JavaFX application.

**Comment by yossigil** [comment]
#11 KARMA++
