### ISSUE TITLE
Create and implement "DatabaseHandler"

### ISSUE THREAD

**Issue by inbalzukerman** [TechnionYP5777/SmartCity-Elderly-Support#52]
for more information: #24 

The class `DatabaseHandler`* is responsible to handle the information in the system. It allows putting and getting it by the sensors and the applications respectively.
\* the name is not final, and the following functionality might be implemented as part of an already existing class

It should include the following functionally:
- Hold information gathered from sensors
- Allow the system to add new content coming from sensors
- Allow the system to create new tables
- Allow the system to add listeners (directly or indirectly) for the tables
- Allow the system to get the gathered information, by direct query or through listeners
- [not final might be moved to future issues] keep a mapping between sensor ID ("MAC") and their commercialName (also refereed to as "type"), and allow the previously mentioned functionalities with both.

In particular, this class should implement the `DatabaseHandlerAPI`. The assignee of this issue is also responsible to refactor the code to use their implementation after the class's completion, and delete the original  `DatabaseHandlerAPI` interface.

**Comment by inbalzukerman** [comment]
@roy-shchory  volunteered to explain pros and cons of  'וmangodb', so we'll consider to use it in the future

In the meanwhile, in sake of accomplishing a working prototype soon, a simpler implementation will be used

**Comment by inbalzukerman** [comment]
Currently left TODO:

- [ ] Create the SensorThread class
- [ ] Create the "SensorHandler" which is a server side of the socket (open for the sensors to register and communicate)
- [ ] Implement the "SensorHandler" methods which are responsible to saving the updates in the system.

**Comment by inbalzukerman** [comment]
Currently left TODO:

- [ ] Create the SensorThread class
- [ ] Create the "SensorHandler" which is a server side of the socket (open for the sensors to register and communicate)
- [ ] Implement the "SensorHandler" methods which are responsible to saving the updates in the system.

**Comment by SharonKL** [comment]
This class will run as a thread and act as a server. It will accept connections from various sensors, allowing them to send information.

To implement this there are two ways:
1. Create a thread for each connection
2. Use the NIO package for advanced connection handling - __better__

**Comment by EliaTraore** [comment]
@SharonKL  your comment suggest a purpose different then what originally described in the issue...
imo we should move this description ("Create the class which is responsible to saving the information ... ") into an issue about a DatabaseHandler (name TBD), and change the description of this issue to something along the lines of your comment. @inbalzukerman, opinions ?

And a question about the sensors - from my understanding we will work with TCP. Is there a special reason for that? reliability isn't that important when your receive so many msgs...

**Comment by SharonKL** [comment]
@EliaTraore I agree, the sensor handler is responsible for handling communication with the sensors, while the database handler will be able to communicate with the database.

As for TCP vs UDP, UDP might be a better option

**Comment by inbalzukerman** [comment]
I agree as well, we should make the separation between the database handler and the sensor handler clear. I will open the relevant issues soon.

**Comment by inbalzukerman** [comment]
@EliaTraore , @SharonKL , @ylevv 

In my opinion this `DatabaseHandler` class is redundant- adding and removing a listener to a sensor's information can be done by calling methods of `SensorHandler` since all the required methods by @EliaTraore are implemented in `SensorInfo`.

All you'll have to do is add some methods in the `SensorHandler` to invoke them for the right sensor (by the sensorID ) and we're done 😄 

Your opinions?

**Comment by EliaTraore** [comment]
Not all the methods are fully implemented in `SensorInfo` (the bugs are mentioned in the appropriate issue - #72)
As far as the ApplicationHandler is concerned, its only a matter of some class implementing the `DatabaseHandlerAPI ` interface. 
Currently, SensorHandler seems like a small class. @SharonKL ,@ylevv, is that expected to change? If not, I don't mind merging them. However, imo they belong in different classes since they preform different tasks.

**Comment by inbalzukerman** [comment]
@EliaTraore - I didn't close #72 because I'm aware to the fact that not all the methods are implemented, don't worry 😄 

I do agree that the tasks meant for `SensorHandler` and `DatabaseHandler`, maybe `MainSystem` can implement the functionalities mentioned for `DatabaseHandler`?

**Comment by EliaTraore** [comment]
@inbalzukerman, mind if I implement this issue?

**Comment by inbalzukerman** [comment]
During a discussion with @EliaTraore , the required functionalities of `DatabaseHandler`, for now, are:

* Add a `ListenableTable` for each sensor which is registering to the system
* Keep a `ListenableTable` for every sensor
* Retrieve the sensor's table for the `SensorHandler`
* Implement the current `DatabaseHandlerAPI`

@SharonKL - this is @EliaTraore 's conclusions mainly, do you have any additions?

**Comment by SharonKL** [comment]
By implementing `DatabaseHandlerAPI` you mean removing the `DatabaseHandlerAPI` interface and moving the functions into `DatabaseHandler`, or keeping the `DatabaseHandlerAPI` interface and letting `DatabaseHandler` implement it? I think the first option is better

**Comment by inbalzukerman** [comment]
The first option it is, the interface itself is only temporary for my understanding.

**Comment by SharonKL** [comment]
![](https://a.fastcompany.net/multisite_files/fastcompany/imagecache/inline-large/inline/2013/11/3021307-inline-fb-thumbsup-printpackaging.jpg)
