### ISSUE TITLE
Convert project to maven

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5777/SmartCity-Elderly-Support#53]
Create a pom.xml etc. Change folder structure.

**Comment by SharonKL** [comment]
A `pom.xml` file already exists: https://github.com/TechnionYP5777/SmartCity-Elderly-Support/blob/master/ElderlySupport/pom.xml

The project was initialized as a maven project by eclipse, and from my understanding it matches the official maven structure: https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html

@yossigil

**Comment by yossigil** [comment]
I thought pom.xml should be at the root, no?

**Comment by SharonKL** [comment]
@yossigil the `pom.xml` file has been deleted from the repository, was it intentional?

**Comment by RonGatenio** [comment]
I added the pom.xml to the root folder https://github.com/TechnionYP5777/SmartCity-Elderly-Support/commit/10a6112c031cadff3fe3a2a655d4f86adbd029f6
@yossigil

**Comment by yossigil** [comment]
Yes. My mistake. K -= 1000
