### ISSUE TITLE
Create an application identifier class

### ISSUE THREAD

**Issue by RonGatenio** [TechnionYP5777/SmartCity-Elderly-Support#54]
An instance of this class will be created after the installation of a new application.
should store:
- [x] unique ID
- [x] a path to it's JAR file

This instance should be saved in the system's database @inbalzukerman @EliaTraore

**Comment by inbalzukerman** [comment]
Looks like this class is implemented, what's missing?

**Comment by RonGatenio** [comment]
The implementation will change. A new issue will be opened...
