### ISSUE TITLE
Create the RegisterMessage class

### ISSUE THREAD

**Issue by SharonKL** [TechnionYP5777/SmartCity-Elderly-Support#57]
This class will implement the Message interface and allow the user to define a register message that will be sent to the system.

**Comment by inbalzukerman** [comment]
@SharonKL - Should be in the System package?
If it is I'll assign myself

**Comment by SharonKL** [comment]
Both the system and sensors packages will use this class, I think it is better to put it in inside the networking package (where I have created the Message interface).

I think @ylevv took this task on her
