### ISSUE TITLE
Create the UpdateMessage class

### ISSUE THREAD

**Issue by SharonKL** [TechnionYP5777/SmartCity-Elderly-Support#58]
This class will implement the Message interface and allow the user to configure an `Update Message` that will be sent to the system.

**Comment by inbalzukerman** [comment]
@SharonKL  same question about the system package 😅

**Comment by SharonKL** [comment]
Both the system and sensors packages will use this class, I think it is better to put it in inside the networking package (where I have created the Message interface).

I think @ylevv took this task on her

**Comment by inbalzukerman** [comment]
@ylevv please talk with us (myself and @EliaTraore  ) to make sure we all agree on the Interface 😄

**Comment by SharonKL** [comment]
Since it affects the 4 of us, we could have the discussion here. We already agreed on the fact that the messages sent will be a JSON format, my suggestion for the structure of such message is the following:

```json
{
    "type": "registration",
    "id": "<sensor id>",
    "type": [
        "<sensor type 1>",
        "<sensor type 2>",
    ]
}
```

The type parameter is a list because one sensor might supply multiples types of information. Your opinions?

**Comment by inbalzukerman** [comment]
Looks good by my opinion.
We should decide on the options of the types ( an enum maybe?) for the type of the message and also for the type of the sensor so it won't create any problem

**Comment by yossigil** [comment]
:+1:  Sharon re: JSon.

**Comment by SharonKL** [comment]
IMO the types should be defined by string and not enum, as we wouldn't want to re-compile the system each time a new sensor type is added.

I agree about the introduction of an enum for the messages type, it would define the messages in a clearer way (and we are not going to introduce more messages types after the system is released).

@inbalzukerman @EliaTraore 
@ylevv do you mind writing the enum as well, or do you me to do it?

**Comment by ylevv** [comment]
@SharonKL I can write the enum. I think the structure you suggested is a good one.

**Comment by inbalzukerman** [comment]
@ylevv I think we are ready to go
If you need any help talk with me :smile:

**Comment by SharonKL** [comment]
Didn't notice this is the UpdateMessage issue. About this message, I suggest the following JSon structure:

```json
{
    "type": "update",
    "id": "<sensor id>",
    "data": {
        "<parameter #1>": "<value 1>",
        "<parameter #2>": "<value 2>",
        "<parameter #3>": "<value 3>",
    }
}
```

where `parameter 1`, `parameter 2` and `parameter 3` are the parameters the sensor told the system it is going to send. Bearing this in mind, I suggest the following update on the Register Message structure:

```json
{
    "type": "registration",
    "id": "<sensor id>",
    "type": [
        "<sensor type 1>",
        "<sensor type 2>",
    ],
    "observations": [
        "<parameter 1>",
        "<parameter 2>",
        "<parameter 3>"
    ]
}
```

@inbalzukerman @EliaTraore @ylevv

**Comment by inbalzukerman** [comment]
Looks good, noticed 👍

**Comment by SharonKL** [comment]
Done 💪  (The `UpdateMessage` class)
