### ISSUE TITLE
Fix documentation

### ISSUE THREAD

**Issue by inbalzukerman** [TechnionYP5777/SmartCity-Elderly-Support#59]
TODOs for other people should be tagged or mentioned in their "Todo" page for example;
And- documentation should be more readable 😅  😪 

![image](https://cloud.githubusercontent.com/assets/23147895/21080258/6e39fd68-bfb3-11e6-88db-984d05d0b7ce.png)

**Comment by inbalzukerman** [comment]
@EliaTraore ?

**Comment by EliaTraore** [comment]
this is a TODO comment, and as such it will be deleted when what needs to be done is done. the javadoc comments on the other hand, are written in a professional manner.
and while we clearly not allowed to have fun with this project, i think some humor in futurely-deleted comments shouldn't be that critical.
i will how ever tag the appropriate TODO issues in the future.
