### ISSUE TITLE
Complete the "Main menu" sub-section 

### ISSUE THREAD

**Issue by inbalzukerman** [TechnionYP5777/SmartCity-Elderly-Support#6]
Complete the "Main menu" sub-section in the Software Implementation part of the first report by Sunday, November the 27th.

**Comment by SharonKL** [comment]
@zvili @idabran What are we supposed to write in this sub-section? An explanation of how the main menu interface will look like? What options will be given to the user using the program we will supply?

**Comment by inbalzukerman** [comment]
After reconsidering, found unnecessary
