### ISSUE TITLE
JSon-lib : add dependency to the pom.xml and a wiki page 

### ISSUE THREAD

**Issue by inbalzukerman** [TechnionYP5777/SmartCity-Elderly-Support#61]
* Add to the pom.xml the relevant dependencies 
* Add a wiki page with explanations and instructions.

**Comment by SharonKL** [comment]
GSon library was already added to the dependencies, I can write a short wiki page about it if you want

**Comment by inbalzukerman** [comment]
@SharonKL  sorry I didn't notice that 😞 
If you have the time, go for it
Your wiki reputation goes ahead of you 😄 😊

**Comment by inbalzukerman** [comment]
The Gson lib dependency was added to the pom.xml by @SharonKL and fixed by me
A wiki page is unnecessary since the tutorials found online and the API is very clear

Issue is done
