### ISSUE TITLE
FIX: Commits are failing

### ISSUE THREAD

**Issue by inbalzukerman** [TechnionYP5777/SmartCity-Elderly-Support#62]
Commits are failing for some reason:

![image](https://cloud.githubusercontent.com/assets/23147895/21083549/6bc02326-bffb-11e6-8319-e4cbda223364.png)

Error log is:

![image](https://cloud.githubusercontent.com/assets/23147895/21083554/7d8afaa4-bffb-11e6-9b09-c9aac702e095.png)

**Comment by inbalzukerman** [comment]
I think i managed to fix the bug, please make a commit (even not with a big change) to make sure everything is back to normal, and make sure the work you had didn't get lost somehow:

- [ ] Sensors team - @SharonKL  or @ylevv 
- [ ]  Appications team - @RonGatenio  or @roy-shchory

**Comment by RonGatenio** [comment]
Looks like it works now, good job @inbalzukerman 👍

**Comment by inbalzukerman** [comment]
Done, now all works fine 😄
