### ISSUE TITLE
Create an Application Manager class

### ISSUE THREAD

**Issue by RonGatenio** [TechnionYP5777/SmartCity-Elderly-Support#65]
This class should manage a single application.
The class will store the following information about the application:
- id
- location of .jar file
- SmartHouseApplication instance
- storage place in database

# Managing an App
- Will allow to create a new App from jar, or to load if already exists.
- Will help communicate with the system (the system will use this object to reference the applications) #26 @EliaTraore 
- Will handle all threads of the app
- Call the app's functions via the SmartHouseApplication API

**Comment by inbalzukerman** [comment]
@RonGatenio shouldn't this issue be part of the Bunny milestone?

**Comment by RonGatenio** [comment]
did this one already...
