### ISSUE TITLE
Implement "SensorInfo"

### ISSUE THREAD

**Issue by inbalzukerman** [TechnionYP5777/SmartCity-Elderly-Support#72]
Will hold the information received from a sensor, a list of the listeners (applications) to updates from this sensor and will include all needed getters and setters.

**Comment by inbalzukerman** [comment]
@SharonKL - I saw your implementation of `SensorHandler` and I see you are using a `HashMap` from the sensorID to it's `SensorInfo ` instance
Therefore I think saving the sensor's id in `SensorInfo ` is redundant.
I would like to hear your opinion and if you agree with me I'll make the necessary changes 😄

**Comment by SharonKL** [comment]
@inbalzukerman Didn't look too much into this, but seems pretty redundant for now 😃

**Comment by EliaTraore** [comment]
Current implementation have a list of listeners, but they are never called. imho they should be called at `addRecord` method.

**Comment by inbalzukerman** [comment]
@EliaTraore - I'm aware of this problem, I wanted to discuss it with you first (to understand how `ApplicationHandler` will be sending the data (listeners) and to think with you about the implementation. Unfortunately being sick+ working all week didn't work out as well as I hoped and I overslept 😞 😳

**Comment by EliaTraore** [comment]
first of all, get well :bouquet::smile: 
And we'll have to postpone this discussion to the aftermath of #73

**Comment by inbalzukerman** [comment]
After the discussion in the legendary #73 (here you go @EliaTraore ), this class is declared redundant and will be removed soon.

**Comment by inbalzukerman** [comment]
@SharonKL - `DatabaseHandler` is updated and implemented, for your use in order to update `SensorsHandler`.
`SensorInfo` can only be deleted after you'll make the necessary changes in `SensorsHandler`.

**Comment by SharonKL** [comment]
Will do when I come back from work - in the meantime could you please make the types in the `Table` class less restrictive (here i gave an example for some locations https://github.com/TechnionYP5777/SmartCity-Elderly-Support/commit/d051f4447d233cb41323426a69cb61ded6d424de)

@inbalzukerman

**Comment by inbalzukerman** [comment]
@SharonKL sure thing, asap 👍

**Comment by SharonKL** [comment]
Methods in `SensorHandler` have been implemented and `SensorInfo` removed
