### ISSUE TITLE
Settling the CommercialName subject

### ISSUE THREAD

**Issue by EliaTraore** [TechnionYP5777/SmartCity-Elderly-Support#74]
As past-Sharon and past-Elia compromised in the legendary #73,  any `commercialName` field defined in the applications-system API will be used as a MAC-ID field, meaning that the MAC-ID will be sent instead of the COM-NAME (which wasn't documented in the code, cuz we're edgy af).
This is of course a temporary work-around, since there's no injective (1-to-1) relation between MACs and COMs.  
<br>
This issue will be closed after a definitive solution have been reached. Meaning that there's a way that the applications can ask or have an ID of the sensor they want to use in the system.
glhf!

**Comment by SharonKL** [comment]
Settled? @EliaTraore

**Comment by EliaTraore** [comment]
yeah :smile: #firstClosedIssueOfTheMileStone
