### ISSUE TITLE
Further develop the system-apps interface ["ApplicationHandler"] 

### ISSUE THREAD

**Issue by EliaTraore** [TechnionYP5777/SmartCity-Elderly-Support#75]
Currently the only needed functionalities that wasn't implemented in the corresponding Alpaca-milestone issue (#26)  are:
- [x] Remove the ability to cancel a listener registration, a la app team request
- [x] Allow getting the sensorsID compatible to a certain commercial name
meaning implement: 
`List<String> InqireAbout(String sensorCommercialName)` 
(will require updates in the structure of `databaseHandler` from the Alpaca-implementation).
- [ ] Receive alerts on abnormalities from the applications and contact the right authority (see #23) 
meaning implement: 
`void alertOnAbnormalState(final String appId, final String message, final EmergencyLevel eLevel)`
The whole user information issue (#48) was postpone to future milestone. When it will be put back to motion, there will be a need to add this functionality.
- [x] Develop (hopeful fully) the process of installing/loading and running the application on from within the system.

<br>
when all the aforementioned features are implemented, the issue will be closed.

**Comment by EliaTraore** [comment]
@yossigil com'on that nitpicking :stuck_out_tongue_winking_eye: 
![father vs further](https://cloud.githubusercontent.com/assets/23057223/21293142/7033ffa8-c524-11e6-9d2c-a3e5ce4a7ca6.png)

**Comment by EliaTraore** [comment]
_ahem last bullet ahem_ @RonGatenio

**Comment by yossigil** [comment]
Keep up the good spirit!

**Comment by EliaTraore** [comment]
see closing comment of #108 for details on the `alert` method implementation. Since #108 was closed, this one can be closed as well.
