### ISSUE TITLE
Modify the Database to keep json msgs from the sensors

### ISSUE THREAD

**Issue by EliaTraore** [TechnionYP5777/SmartCity-Elderly-Support#77]
Being that the applications team requested the method defined in #76, and prefer it over the existing methods (which return a table), there's no need in converting the json msg to a table entry.
Keeping a list of json msgs instead of a table will make implementing #76 much easier, and make the system simpler.

This issue will be closed when the `DatabaseHandler` have a method receiving a json msg (in which it will keep it as is in the appropriate list) Alt. - changing the implementation of `addRecord` in `ListenableTable` to receive a json msg and keep it.

**Comment by inbalzukerman** [comment]
@EliaTraore  @SharonKL -
If I will change `DatabaseHandler` to keep a list of JSon messages, the functionality added thanks to the `ListenableTable` to the current implementation will be lost and the mechanism of informing all the listeners will have to be implemented differently. 
In this matter- what are your opinions on implementing this issue using a `ListenableList`, which will function as a replacement to the `ListenableTable`?

**Comment by SharonKL** [comment]
Support the idea of the `ListenableList`, I would suggest implementing it before changing the `DatabaseHandler`

**Comment by inbalzukerman** [comment]
This is the idea, I can implement it right now 👍 
@EliaTraore ?
