### ISSUE TITLE
Refactor "sensorId" and "sensorID" to one consistent version throughout the project 

### ISSUE THREAD

**Issue by EliaTraore** [TechnionYP5777/SmartCity-Elderly-Support#79]
As @yossigil  mentioned, "Id" would be the java convention, but the assignee of this issue get the freedom to choose (!!!!)

**Comment by yossigil** [comment]
:+1:

**Comment by EliaTraore** [comment]
There's still inconsistency in`DatabaseHandler`/ Didn't check for other places but maybe sensor related classes too

**Comment by yossigil** [comment]
Keep up the good work :-)
