### ISSUE TITLE
Limit the amount of messages sent by each sensors

### ISSUE THREAD

**Issue by SharonKL** [TechnionYP5777/SmartCity-Elderly-Support#81]
Since we chose to move to TCP and don't want to overload the system with too many messages, we decided to limit the amount of messages each sensor is able to send each second.

This issue will be closed once we were able to achieve this goal.

**Comment by SharonKL** [comment]
I see two options:

* Create a buffer of messages to be delivered, and make sure to only send at most `x` messages per interval of time. The problem is, that if the sensor produces more messages than messages are being sent, this buffer will keep growing.
* Discard any message that exceeds this limit. We could also let sensors manufactures know about this limit and they will be able to limit the sensor itself to this amount of messages per interval of time.

opinions?

**Comment by SharonKL** [comment]
I will keep the `help wanted` label in case someone wants to participate in this decision

**Comment by inbalzukerman** [comment]
In my opinion the second option is better and somewhat less "risky". I would go with this approach if it was up to me

**Comment by EliaTraore** [comment]
The second option doesn't really protect us from ignoring a crucial msg ("sos button was pressed" for example).
Is overloading the system really a possibility? Maybe we should conduct stress tests or look into some documentation to try to assess the risk here. Since if it's not, it seems to me like we're better off leaving the msgs unlimited.
If it really is a possiblity, option 2 + a manner of marking ergent msgs is the best approach imo.

**Comment by SharonKL** [comment]
Unless the elderly will furiously press the sensor button more than 100 times in one second, the SOS sensor wouldn't be affected by this change

**Comment by EliaTraore** [comment]
Well he might but in that case there will be 100 msgs from the SOS sensor so we're still golden lol
So there's no chance of losing important data as a result of limiting the msgs?

**Comment by SharonKL** [comment]
100 messages in one second? that's some next level parkinson

We might lose data, but we are dealing with actions concerning human being, that usually don't observe more than 100 actions a second. Even if we discard one message saying the stove has exceeded 1000 celsius, we will receive it in the next update that will come in several milliseconds.

**Comment by SharonKL** [comment]
I will take the likes as agrrement 😁

**Comment by inbalzukerman** [comment]
Even my heartrate doesn't change **that** fast 😲 
I think we're good with the second option then :grinning:

**Comment by SharonKL** [comment]
done
