### ISSUE TITLE
Add console to stove sensor simulator

### ISSUE THREAD

**Issue by SharonKL** [TechnionYP5777/SmartCity-Elderly-Support#82]
The console will show what and when messages are sent from the simulator to the system, to better debug and see changes.

**Comment by yossigil** [comment]
Marvelous idea @SharonKL

**Comment by SharonKL** [comment]
![](https://s23.postimg.org/g0vm6obqj/Stove_Sensor_GUI_Demonstration.gif)

Done, with colors 😄
