### ISSUE TITLE
Add commercial name to registration message

### ISSUE THREAD

**Issue by SharonKL** [TechnionYP5777/SmartCity-Elderly-Support#84]
When a sensor registers, it should also send its commercial name.

**Comment by yossigil** [comment]
What's a "commerical" name?

**Comment by EliaTraore** [comment]
Its the name by which its company advertises its sensor. Say you have chairs with pressure sensors in them, helping to monitor the elder's movement  (or lack thereof). One company might call it a "hiney sensor" while the other will call it "iButtocks sensor", and those are their commercial names. 
When an application will install on the system it wil first inquire about the existence of the sensors its willing to work with, referring to them by those name.

**Comment by SharonKL** [comment]
Done
