### ISSUE TITLE
Update The "DatabaseHandler" to keep and use commercial names

### ISSUE THREAD

**Issue by EliaTraore** [TechnionYP5777/SmartCity-Elderly-Support#85]
- [x] Add a mapping between the commercial names to the sensorIDs, preferably `Map<String, List<String>>` since there could be couple of sensrIDs under the same commercial names .
- [x] Update the registration method (which allocates a table for the sensor) to have a `String commercialName` field. ~Opt - keep the original method as legacy, and change it implementation to define the commercialName to be the sensorID (as in "if there isn't a commercialName, the ID becomes the commercial name")~

**Comment by EliaTraore** [comment]
@SharonKL  -  Is the opt. part needed? or would you rather have only one method of registration?

**Comment by SharonKL** [comment]
Don't think its needed, we will require from sensors to send their commercial name (pretty reasonable I think)

@EliaTraore

**Comment by EliaTraore** [comment]
Remember a15ec62?
@SharonKL  uses comm name instead of ID, @EliaTraore is happy :rofl:

**Comment by roy-shchory** [comment]
![whatsapp image 2016-12-22 at 12 11 44](https://cloud.githubusercontent.com/assets/23057062/21422349/f03a2e34-c83f-11e6-9517-b6aec4750dfa.jpeg)

**Comment by SharonKL** [comment]
We are still going to use IDs 😮

**Comment by SharonKL** [comment]
Done, added tests for most methods in the class
