### ISSUE TITLE
Write tests to check the communication between the system and the sensors

### ISSUE THREAD

**Issue by ylevv** [TechnionYP5777/SmartCity-Elderly-Support#86]
These tests should verify the correctness of the protocol that was established between the system and the sensors in the previous milestone (Milestone Alpaca).

We can start working on this issue after issues #80 and #83 are done.

**Comment by yossigil** [comment]
https://github.com/TechnionYP5777/SmartCity-Market/wiki/Dependency-Injection-and-Unit-Testing-With-Mockito

**Comment by SharonKL** [comment]
Although not a full integration test, but the communication has been fixed and messages can pass from one side to another:

![](https://s24.postimg.org/3rwt4cjd1/integration_system_sensor.gif)

Messages are sent from the sensor (a stand alone application) to localhost using the loop back IP and are received by the sensors handler (a thread running from the SystemCore). In the gif:

* The upper window is the stove sensor simulator
* The lower console is the output generated by the system (the sensors handler thread)
