### ISSUE TITLE
Add GUI for the sensors' information 

### ISSUE THREAD

**Issue by inbalzukerman** [TechnionYP5777/SmartCity-Elderly-Support#89]
see #88 
After choosing a sensor from the list, the information available in the system regarding this sensor should be shown

**Comment by SharonKL** [comment]
Two questions:

1. Do we want it to be a separate window, instead of having a "mini window" in the system GUI?
2. What information should it contain? I can think about:
  * Sensor name
  * Sensor ID
  * Time of registration (?)
  * A console with received messages from the sensor (?)

**Comment by inbalzukerman** [comment]
In my opinion, both a "mini window" and a new separate window are good options, this is up to whoever will assign to this issue to decide 😄 

The information which should be included imo:
* Sensor name
* Sensor ID
* Show current mapping and add an option to change it

I think that the console might be redundant since the applications should "deliver" this information, what do you think @SharonKL ?

Time of registration is a possibility even though I don't think it is very useful information. If we decide to add this, we should add the functionality of saving this information in the system. Do you think it is valuable information @SharonKL ?

@EliaTraore any opinions in this matter? This is only how I see the GUI 😅

**Comment by SharonKL** [comment]
Yeah the time of registration was a pretty forced idea, isn't very usefull.
What do you mean the application should deliver this information? The application simply fetches info from tables and does some magic behind the scenes. By console I mean that we can visually see when the system receives messages (debug reasons, show something to class, etc...).

As for who gets to decide how it looks, I think it would be better to have a discussion (perhaps **after** someone has created a prototype for the GUI) with some team members to get the best look for the GUI.

**Comment by inbalzukerman** [comment]
I agree that the finialization of the GUI design should take place in a bigger forum, I meant for the prototype design.
About the applications- they are responsible for the magic ( 🎉 ) but they are also responsible to show the information received from the sensors in a convenient way (for example the stove sensor's application shows it current known temperature and the vitals sensor's application will show the pulse and blood pressure).

Do you think showing this information also in the sensors' part of the system GUI is required?

**Comment by SharonKL** [comment]
We can leave it out for now, but I think the information shown in the application GUI is different than the raw information sent to the system from the sensor.

So to summarize this discussion as of now, the window will show:

* Sensor name
* Sensor ID
* Sensor mapping (and allow to change it)
* _maybe in the future a console with incoming info_

**Comment by EliaTraore** [comment]
Sounds good to me except - 
- Changing the mapping - wouldn't that be problematic to all the apps relaying on the current location? Unless you're seeing a clear solution that I don't, I think the functionality of changing the location should be left to chipmunk+
- What would be the use of the console? beyond debugging, I couldn't think of a purpose for it...

**Comment by SharonKL** [comment]
* Apps shouldn't be able to handle location changes? (what if we want to move a butt sensor from the couch to the toilet) And you need to have an option to set the location somewhere in the system, I think the sensor GUI is a good place
* dunno, looks impressive? ☺️

**Comment by inbalzukerman** [comment]
I agree with @SharonKL about the location settings 👍

**Comment by EliaTraore** [comment]
- They should, but they need to be notified about that. Move a pressure sensor from the bed to the toilet and you might have a dead man in the bathroom for hours before the application consider alerting any authority. Currently we don't keep record of the sensors each app listens to, so I think notifying on change of location would be a non-trivial task, not to mention not a pressing one. So is it really needed at this point?
-  Essentials before additional :wink:  
Tho as long as its not that much trobule, as you wish :smile:

**Comment by SharonKL** [comment]
I think we can talk about that in the next meeting and meanwhile not pay to much attention to this issue - anyways we currently have only one sensor that can only be in one place (and even if we add the S.O.S sensor until next meeting, its functionallity is location independant).

**Comment by inbalzukerman** [comment]
In our meeting today (3.1) we've decided to present the sensors' information in the GUI described in #113 . Therefore this issue can be closed.

**Comment by SharonKL** [comment]
Kunini the issue killer
