### ISSUE TITLE
First Report is Done

### ISSUE THREAD

**Issue by inbalzukerman** [TechnionYP5777/SmartCity-Elderly-Support#9]
@idabran @zvili @yossigil 

Our first report is to be found in the following link:
https://docs.google.com/document/d/1OY1iSeRCgkJI9jjNh3pCssqRkkCPj-HlBT0AwvcS3T4/edit?usp=sharing

We hope to hear your opinions and comments!
If there is any other format you would like to receive the report please let us know (should we email you a pdf file?)

Thank you 😄 
@SharonKL @ylevv @roy-shchory @RonGatenio @EliaTraore

**Comment by zvili** [comment]
@inbalzukerman - There is only ONE place to store ALL project related documents, i.e., GitHub Wiki.
No other document formats (e.g. googledocs) will be accepted.
Please act accordingly.
:-1:

**Comment by inbalzukerman** [comment]
@zvili - Will do

Didn't know, sorry 😞

**Comment by inbalzukerman** [comment]
The Wiki page "First Report" was added

@zvili

**Comment by zvili** [comment]
@inbalzukerman & team,
I like your report. :+1: 
Your next mission is to define your "project"; you should define a column named "Backlog" and populate it with "user stories" prioritized by importance.
Once this is completed, define 2 more columns: Sprint1 and Sprint2.
We will together review your set of user stories and define the contents of Sprint1 and Sprint2. 
Any questions ?

**Comment by zvili** [comment]
@inbalzukerman & team:
We'll meet tomorrow, Monday @ 16:30 Taub 5.
Your project should include the complete set of user stories.
It is still empty 👎 
@idabran

**Comment by yossigil** [comment]
This issue does not make any sense. Phrase it as something to do, and close it when this is done.
@SharonKL : Please take a cup of bad Karma and drink it. What's your question has to do with the issue? You waste bandwidth.

@zvili @idabran
