### ISSUE TITLE
Rename MainSystem and change to singleton

### ISSUE THREAD

**Issue by SharonKL** [TechnionYP5777/SmartCity-Elderly-Support#90]
My suggestion is:

* Rename `MainSystem` to `SystemCore` to better represent the role of this class (the class is not the whole system, it is the core that combines all the parts).
* Change the class into a singleton, since only one is required for the system to work (no multi cores for us).

@inbalzukerman @EliaTraore opinions?

**Comment by EliaTraore** [comment]
Name 👍 
As for the singleton, I thought of that as well but as @RonGatenio mentioned, that could be annoying when we actually test the core... Is it worth it?

**Comment by SharonKL** [comment]
annoying?

**Comment by inbalzukerman** [comment]
Sounds good 😄 
@SharonKL do you want me to rename? working on couple of things right now anyway 😅

**Comment by yossigil** [comment]
Folks, just FYI, Java conventions are to start packag names with org name.
I suggest: il.ac.technion.cs.XXX
also package names are typically lower case

**Comment by inbalzukerman** [comment]
@yossigil  the `SystemCore` class is in the `il.ac.technion.cs.eldery.system` package. As I understand it all conventions are saved 👍 

I think the confusion might be originated from `SystemCore` : its a class, not a package

**Comment by yossigil** [comment]
Thanks
