### ISSUE TITLE
Implement a getIcon method to the applicationManager

### ISSUE THREAD

**Issue by EliaTraore** [TechnionYP5777/SmartCity-Elderly-Support#91]
The method will allow the system to get an icon representing the application for GUI purposes

**Comment by RonGatenio** [comment]
I actually removed this feature before... no icons for us

**Comment by inbalzukerman** [comment]
![image](https://cloud.githubusercontent.com/assets/23147895/22176214/d659667a-e00d-11e6-8504-eeaffc2c9cd7.png)

Don't forget to remove your TODO 😄

**Comment by RonGatenio** [comment]
oops... 
I already removed this, just didn't commit yet 😅 
thanks
