### ISSUE TITLE
Write more tests for the SensorsHandler class

### ISSUE THREAD

**Issue by SharonKL** [TechnionYP5777/SmartCity-Elderly-Support#96]
Need to think how we test this class - how do we test a server that waits for incoming messages (send them ourselves in the test?)?

**Comment by yossigil** [comment]
Search testing libraries and tools.

**Comment by yossigil** [comment]
dependency injection? search facebook group

**Comment by SharonKL** [comment]
We are aware of `Guice` (Software Design 😄) but this class has been changed since this issue was opened and its functionality and purpose as well. Currently it doesn't hold much functionality to be tested, so we decided to close this issue for now. We might open a new issue in the future regarding testing this class.

**Comment by yossigil** [comment]
👍
